[package]
name = "plugin_system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
snafu = "0.8.2"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
wasmtime = "20.0.2"
